### ISSUE TITLE
Responsive Page

### ISSUE THREAD

**Issue by Pratikn65** [usha-madithati/esmart.github.io#43]
### Describe the feature

I can make the page responsive.
Please assign me this issue. GSSoc'24

### Add ScreenShots

![Screenshot 2024-05-11 143402](https://github.com/usha-madithati/esmart.github.io/assets/138359558/cec6ffbb-49da-4c48-bbe3-8c4c4fd215eb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pat25Taylor** [comment]
I would want to take up this issue please assign it to me.

**Comment by Silentman87** [comment]
dear @usha-madithati  i would like to work on it please asign me

**Comment by JanitKumar** [comment]
@usha-madithati please assign this issue to me I have good experience in solving these kind of issues.

**Comment by harshitpnd12** [comment]
please assign me this issue

**Comment by Srujitha-Raghava** [comment]
Heyyy @usha-madithati 
Ensuring that our webpage is responsive is crucial for providing a seamless user experience across various devices and screen sizes. I'm eager to address this issue and make the necessary adjustments to improve the responsiveness of our webpage.

To make the webpage responsive, I plan to implement the following strategies:
1.Utilize CSS media queries to apply different styles based on the device's screen size.
2.Use relative units like percentages, ems, or viewport width to define sizes, allowing elements to scale appropriately.
3.Implement flexible layouts using CSS Flexbox or Grid Layout to accommodate different screen sizes.
4.Optimize images and media files for responsiveness using techniques such as srcset and sizes.
5.Test the webpage thoroughly on various devices and screen sizes to ensure responsiveness.

kindly assign me this issue under gssoc,so that i can work on

**Comment by n14rishitha** [comment]
Hi @usha-madithati 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3.
