### ISSUE TITLE
Feat:create service and review section

### ISSUE THREAD

**Issue by MrPC7** [usha-madithati/esmart.github.io#86]
### Describe the feature

I will create a services and review section, link it to the navigation bar, and ensure it is responsive for different devices.

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/91939963/041ac3a6-16ed-4b39-bf1a-11b7d7a3b079)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Priyanshu2743** [comment]
Hare Krishna @usha-madithati 

##Describe the feature

I would like to add a Reviews Page for your website, that will be heavily adorned with CSS features ensuring that it will be responsive for different devices.

I would like a lot if add the labels of GSSoC-24 and level 2 to this issue. 
Also, please assign this issue to me and I will get to it right away.
 
Add Screenshots
This is a screenshot of a website made by me for the college project in this the reviews are rotating after 6 seconds so that anybody can read it but no need to scroll

I have also a lot of designs like these
<img width="627" alt="Screenshot 2024-05-14 144128" src="https://github.com/usha-madithati/esmart.github.io/assets/124867297/16eccb9a-3ac2-4f96-9f1f-ed43c3c11545">


##I would like a lot if add the labels of GSSoC-24 and level 2 to this issue. 
##Also, please assign this issue to me and I will get to it right away.
