### ISSUE TITLE
[Feature] : About page

### ISSUE THREAD

**Issue by sivaprasath2004** [usha-madithati/esmart.github.io#92]
### Describe the feature

- Add the `About` page section because this is more `user-friendly`
- I will ready for the feature work it.

### Add ScreenShots

- 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by cpratik1307** [comment]
@sivaprasath2004 Sir, I am willing to work on this feature. Please assign me this issue.

**Comment by Priyanshu2743** [comment]
Hare Krishna @usha-madithati

#Describe the feature
I would like to create an about Page for your website so that it is more user-friendly, that will be heavily adorned with CSS features ensuring that it will be responsive for different devices.

I would like a lot if add the labels of GSSoC-24 and level 2 to this issue.
Also, please assign this issue to me and I will get to it right away.

Add Screenshots
This is a screenshot of a website not made by me 
but I can easily make like this and better that this a lot is you assign me
![image](https://github.com/usha-madithati/esmart.github.io/assets/124867297/e0a91d78-3266-4e69-a31b-4e289e85ff2d)

# I would like a lot if add the labels of GSSoC-24 and level 2 to this issue.
# Also, please assign this issue to me and I will get to it right away.
